name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: ll
      run: ls -l
    - name: make test
      run: make test
